print = ("Type'encode' to encrypt ,  type'decode' to decrypt")
msg = input('Type your message:')
num = input('Type the shift:')
print(f"Here's the {msg} result:")
again = input("type 'yes' if you want to go again, otherwise type 'no':")