print('Welcome to the PyPassword Generator!')
letter = input('How many letters would you like in your password?')
symbol = input('How many symbols would you like?')
number = input('How many numbers would you like?')
pass == input()
print(f"Here is your password: {pass}.")